/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.compilers.first.lab;

import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sjdonado
 */
public class GUI extends javax.swing.JFrame {
    private AbstractSyntaxTree tree;
    private DefaultTableModel jTableTreeModel;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        jPanelTree.setBorder(new EmptyBorder(5, 5, 5, 5));
        jPanelTree.setLayout(new BorderLayout(0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editRegex = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuildRegexTree = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTree = new javax.swing.JTable();
        jPanelTree = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        editEvaulateRegex = new javax.swing.JTextField();
        btnEvaluateRegex = new javax.swing.JButton();
        textEvaluationResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editRegex.setText("(a|b)*abb");
        editRegex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRegexActionPerformed(evt);
            }
        });

        jLabel1.setText("Expresión regular:");

        btnBuildRegexTree.setText("Aceptar");
        btnBuildRegexTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuildRegexTreeActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTableTree);

        jPanelTree.setPreferredSize(new java.awt.Dimension(800, 400));

        javax.swing.GroupLayout jPanelTreeLayout = new javax.swing.GroupLayout(jPanelTree);
        jPanelTree.setLayout(jPanelTreeLayout);
        jPanelTreeLayout.setHorizontalGroup(
            jPanelTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelTreeLayout.setVerticalGroup(
            jPanelTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setText("Reconocer cadena:");

        editEvaulateRegex.setText("abbabb");
        editEvaulateRegex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEvaulateRegexActionPerformed(evt);
            }
        });

        btnEvaluateRegex.setText("Aceptar");
        btnEvaluateRegex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluateRegexActionPerformed(evt);
            }
        });

        textEvaluationResult.setText("No valida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelTree, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editRegex, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuildRegexTree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editEvaulateRegex, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEvaluateRegex)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textEvaluationResult)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editRegex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuildRegexTree)
                    .addComponent(jLabel2)
                    .addComponent(editEvaulateRegex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEvaluateRegex)
                    .addComponent(textEvaluationResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTree, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuildRegexTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuildRegexTreeActionPerformed
        this.tree = new AbstractSyntaxTree(editRegex.getText());
        
        JPanel drawTree = new DrawTree(this.tree);
        jPanelTree.removeAll();
        jPanelTree.add(drawTree);
        revalidate();
        repaint();
        
        ArrayList<String[]> treePositions = this.tree.getTreePositions();
        jTableTreeModel = new DefaultTableModel(treePositions.size(), 4);
        jTableTreeModel.setColumnIdentifiers(new String[] { "Nodo", "PrimeraPos",
            "ÚltimaPos", "SiguientePos"});
        
        for (int row = 0; row < treePositions.size(); row++) {
            String[] nodePositions = treePositions.get(row);
            jTableTreeModel.setValueAt(nodePositions[0], row, 0);
            jTableTreeModel.setValueAt(nodePositions[1], row, 1);
            jTableTreeModel.setValueAt(nodePositions[2], row, 2);
            jTableTreeModel.setValueAt(nodePositions[3], row, 3);
        }
        
        jTableTree.removeAll();
        jTableTree.setModel(jTableTreeModel);
    }//GEN-LAST:event_btnBuildRegexTreeActionPerformed

    private void editRegexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRegexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editRegexActionPerformed

    private void editEvaulateRegexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEvaulateRegexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEvaulateRegexActionPerformed

    private void btnEvaluateRegexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluateRegexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEvaluateRegexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame jframe = new GUI();
                jframe.setLocationRelativeTo(null);
                jframe.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuildRegexTree;
    private javax.swing.JButton btnEvaluateRegex;
    private javax.swing.JTextField editEvaulateRegex;
    private javax.swing.JTextField editRegex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelTree;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTree;
    private javax.swing.JLabel textEvaluationResult;
    // End of variables declaration//GEN-END:variables
}
